# I] Import

In [1]:
import pandas

# II] ATG7 isoform expression

In [5]:
%%time
# DL data ATG7 isoform expression
input_file_directory_gene_expr = '/Users/kja11/OneDrive - Háskóli Íslands/PhD ATG7/0 Python Analysis/gene_expr_preparation/'

directory = input_file_directory_gene_expr + "df_ATG7_NormPrim.csv"
df_ATG7_NormPrim= pandas.read_csv(directory, sep = "\t")
print(df_ATG7_NormPrim.shape)
df_ATG7_NormPrim.head()

(16614, 17)
Wall time: 60.9 ms

,sample,Sample_Type,Primary_Site,ATG7,ATG7_1,ATG7_2,ATG7_3,ATG7_total,ATG7_1tpm,ATG7_2tpm,ATG7_3tpm,ATG7_prot_tot,ATG7_1perc,ATG7_2perc,ATG7_3perc,ATG7_1norm,ATG7_2norm
0,GTEX-ZTTD-0326-SM-57WFW,Normal Tissue,Muscle,5.042,3.860,2.390,0.2642,5.085097,3.955992,2.641679,1.199970e+00,7.797641,50.733194,50.733194,50.733194,0.777958,0.777958
1,GTEX-PX3G-1626-SM-2S1PT,Normal Tissue,Muscle,4.252,2.322,1.956,1.1320,4.325725,2.584782,2.286540,2.190624e+00,7.061946,36.601554,36.601554,36.601554,0.597537,0.597537
2,GTEX-OXRO-1726-SM-3LK6C,Normal Tissue,Muscle,3.909,2.602,1.345,-9.9660,4.001888,2.821767,1.823465,-1.495113e-07,4.645231,60.745450,60.745450,60.745450,0.705109,0.705109
3,GTEX-13JVG-0126-SM-5L3D3,Normal Tissue,Muscle,3.854,2.568,1.428,-9.9660,3.950379,2.792620,1.883517,-1.495113e-07,4.676137,59.720662,59.720662,59.720662,0.706924,0.706924
4,GTEX-NPJ8-1626-SM-2HMIY,Normal Tissue,Muscle,3.822,2.164,1.293,-1.5100,3.920469,2.454322,1.786333,3.501112e-01,4.590767,53.462146,53.462146,53.462146,0.626028,0.626028

In [11]:
#split to have Normal (GTEX) and Primary (TCGA)
df_ATG7_Normal = df_ATG7_NormPrim[df_ATG7_NormPrim['sample'].str.startswith('GTEX')]
print(len(df_ATG7_Normal))
df_ATG7_Primary = df_ATG7_NormPrim[df_ATG7_NormPrim['sample'].str.startswith('TCGA')]
print(len(df_ATG7_Primary))

7429
9185

## A) ATG7 isoforms + Whole gene expression (ensembl)

In [3]:
%%time
# DL data gene expression for Normal Tissue and Primary Tumors
input_file_directory_gene_expr = '/Users/kja11/OneDrive - Háskóli Íslands/PhD ATG7/0 Python Analysis/gene_expr_preparation/'

directory = input_file_directory_gene_expr + "ensembl_normal_liver_protcoding_expr.csv"
ensembl_normal_liver_protcoding_expr= pandas.read_csv(directory, sep = "\t")
print(ensembl_normal_liver_protcoding_expr.shape)

directory = input_file_directory_gene_expr + "ensembl_primary_liver_protcoding_expr.csv"
ensembl_primary_liver_protcoding_expr= pandas.read_csv(directory, sep = "\t")
print(ensembl_primary_liver_protcoding_expr.shape)
ensembl_primary_liver_protcoding_expr.head()

(7429, 19383)
(9185, 19383)
Wall time: 3min 28s

,sample,ENSG00000198888,ENSG00000198763,ENSG00000198804,ENSG00000198712,ENSG00000228253,ENSG00000198899,ENSG00000198938,ENSG00000198840,ENSG00000212907,...,ENSG00000160678,ENSG00000160679,ENSG00000143553,ENSG00000214193,ENSG00000196182,ENSG00000181817,ENSG00000116885,ENSG00000116898,ENSG00000119535,ENSG00000142694
0,TCGA-02-0047-01,12.9202,13.1220,14.0136,13.5251,13.8439,13.7777,13.4037,12.8123,13.4187,...,6.4741,5.8017,6.4975,2.1509,5.2445,6.0507,3.8915,5.5389,4.2936,4.6685
1,TCGA-02-0055-01,10.3972,10.7774,12.3945,12.3893,11.7280,11.9408,12.2022,11.0142,11.0221,...,5.9969,5.6888,6.0633,1.9822,4.3299,6.4992,3.7582,6.7092,4.5964,5.5145

In [13]:
#Preparation of the global dataframe with ATG7 isoform expression AND whole gene expression
data = [[ensembl_normal_liver_protcoding, df_ATG7_Normal], [ensembl_primary_liver_protcoding, df_ATG7_Primary]]

df_final = []

for df in data:
    #Merge the two df to have ATG7 isoform expression + whole gene expression 
  df_merged = pandas.merge(df[1], df[0], on= 'sample')

  #delete the sample column and select column
  df_merged = df_merged.drop("sample", 1)
  df_merged = df_merged.drop(df_merged.columns[5:19], axis=1)
  
  #save in list
  df_final.append(df_merged)

ensembl_normal_liver_protcoding_atg7_expr = df_final[0]
ensembl_primary_liver_protcoding_atg7_expr = df_final[1]

print(ensembl_normal_liver_protcoding_atg7_expr.shape)
print(ensembl_primary_liver_protcoding_atg7_expr.shape)
ensembl_normal_liver_protcoding_atg7_expr.head()

(7429, 19384)
(9185, 19384)

,Sample_Type,Primary_Site,ATG7,ATG7_1,ATG7_2,ENSG00000198712,ENSG00000228253,ENSG00000198899,ENSG00000198938,ENSG00000198840,...,ENSG00000160678,ENSG00000160679,ENSG00000143553,ENSG00000214193,ENSG00000196182,ENSG00000181817,ENSG00000116885,ENSG00000116898,ENSG00000119535,ENSG00000142694
0,Normal Tissue,Muscle,5.042,3.860,2.390,14.4453,15.0971,14.4720,14.7683,13.8143,...,2.7868,5.6494,5.0193,2.6940,4.5274,5.0998,2.3423,6.0790,6.4861,4.9700
1,Normal Tissue,Muscle,4.252,2.322,1.956,14.3855,15.1867,14.8991,14.4038,13.1051,...,9.3501,6.1104,6.0570,1.1770,6.8792,6.4325,2.1013,6.7035,1.1706,1.3167
2,Normal Tissue,Muscle,3.909,2.602,1.345,13.8211,14.8161,14.1107,14.7035,13.2776,...,9.0646,5.9750,5.1173,1.8683,4.6136,5.0090,2.0604,5.7848,1.7489,4.6514
3,Normal Tissue,Muscle,3.854,2.568,1.428,14.0622,15.5897,14.8774,14.5459,13.7788,...,9.2252,5.4941,5.5880,-0.4521,5.6631,6.3797,2.5683,7.3214,1.6140,1.5563
4,Normal Tissue,Muscle,3.822,2.164,1.293,13.4082,14.0564,13.7832,13.5560,13.2383,...,8.9779,6.1502,5.1330,2.0289,6.8202,6.1789,1.8524,6.7685,2.8838,1.8323

In [36]:
#save to csv
ensembl_normal_liver_protcoding_atg7_expr.to_csv('ensembl_normal_liver_atg7_proteinGE.csv', sep = "\t", index=False)
ensembl_primary_liver_protcoding_atg7_expr.to_csv('ensembl_primary_liver_atg7_proteinGE.csv', sep = "\t", index=False)

## B) ATG7 isoforms + Whole gene expression (symbol)

In [14]:
%%time
# DL data gene expression for Normal Tissue and Primary Tumors
input_file_directory_gene_expr = '/Users/kja11/OneDrive - Háskóli Íslands/PhD ATG7/0 Python Analysis/gene_expr_preparation/'

directory = input_file_directory_gene_expr + "symbol_normal_liver_protcoding_expr.csv"
symbol_normal_liver_protcoding_expr= pandas.read_csv(directory, sep = "\t")
print(symbol_normal_liver_protcoding_expr.shape)

directory = input_file_directory_gene_expr + "symbol_primary_liver_protcoding_expr.csv"
symbol_primary_liver_protcoding= pandas.read_csv(directory, sep = "\t")
print(symbol_primary_liver_protcoding.shape)
symbol_primary_liver_protcoding.head(2)

(7429, 19190)
(9185, 19190)
Wall time: 3min 31s

,sample,MT-ND1,MT-ND2,MT-CO1,MT-CO2,MT-ATP8,MT-ATP6,MT-CO3,MT-ND3,MT-ND4L,...,S100A1,CHTOP,SNAPIN,SH3D21,STK40,LSM10,OSCP1,MRPS15,CSF3R,EVA1B
0,TCGA-02-0047-01,12.9202,13.1220,14.0136,13.5251,13.8439,13.7777,13.4037,12.8123,13.4187,...,6.4741,5.8017,6.4975,2.1509,5.2445,6.0507,3.8915,5.5389,4.2936,4.6685
1,TCGA-02-0055-01,10.3972,10.7774,12.3945,12.3893,11.7280,11.9408,12.2022,11.0142,11.0221,...,5.9969,5.6888,6.0633,1.9822,4.3299,6.4992,3.7582,6.7092,4.5964,5.5145

In [15]:
#Preparation of the global dataframe with ATG7 isoform expression AND whole gene expression
data = [[symbol_normal_liver_protcoding, df_ATG7_Normal], [symbol_primary_liver_protcoding, df_ATG7_Primary]]

df_final = []

for df in data:
    #Merge the two df to have ATG7 isoform expression + whole gene expression 
  df_merged = pandas.merge(df[1], df[0], on= 'sample')

  #delete the sample column and select column
  df_merged = df_merged.drop("sample", 1)
  df_merged = df_merged.drop(df_merged.columns[5:19], axis=1)
  
  #save in list
  df_final.append(df_merged)

symbol_normal_liver_protcoding_atg7_expr = df_final[0]
symbol_primary_liver_protcoding_atg7_expr = df_final[1]

print(symbol_normal_liver_protcoding_atg7_expr.shape)
print(symbol_primary_liver_protcoding_atg7_expr.shape)
symbol_normal_liver_protcoding_atg7_expr.head()

(7429, 19191)
(9185, 19191)

,Sample_Type,Primary_Site,ATG7_x,ATG7_1,ATG7_2,MT-CO2,MT-ATP8,MT-ATP6,MT-CO3,MT-ND3,...,S100A1,CHTOP,SNAPIN,SH3D21,STK40,LSM10,OSCP1,MRPS15,CSF3R,EVA1B
0,Normal Tissue,Muscle,5.042,3.860,2.390,14.4453,15.0971,14.4720,14.7683,13.8143,...,2.7868,5.6494,5.0193,2.6940,4.5274,5.0998,2.3423,6.0790,6.4861,4.9700
1,Normal Tissue,Muscle,4.252,2.322,1.956,14.3855,15.1867,14.8991,14.4038,13.1051,...,9.3501,6.1104,6.0570,1.1770,6.8792,6.4325,2.1013,6.7035,1.1706,1.3167
2,Normal Tissue,Muscle,3.909,2.602,1.345,13.8211,14.8161,14.1107,14.7035,13.2776,...,9.0646,5.9750,5.1173,1.8683,4.6136,5.0090,2.0604,5.7848,1.7489,4.6514
3,Normal Tissue,Muscle,3.854,2.568,1.428,14.0622,15.5897,14.8774,14.5459,13.7788,...,9.2252,5.4941,5.5880,-0.4521,5.6631,6.3797,2.5683,7.3214,1.6140,1.5563
4,Normal Tissue,Muscle,3.822,2.164,1.293,13.4082,14.0564,13.7832,13.5560,13.2383,...,8.9779,6.1502,5.1330,2.0289,6.8202,6.1789,1.8524,6.7685,2.8838,1.8323

In [30]:
#Why ATG7_x ?
verif = symbol_normal_liver_protcoding_atg7_expr[symbol_normal_liver_protcoding_atg7_expr.columns[pandas.Series(symbol_normal_liver_protcoding_atg7_expr.columns).str.startswith('ATG7')]]
print(verif.head(2))

   ATG7_x  ATG7_1  ATG7_2  ATG7_y
0   5.042   3.860   2.390  5.0418
1   4.252   2.322   1.956  4.2518

In [33]:
data = [symbol_normal_liver_protcoding_atg7_expr, symbol_primary_liver_protcoding_atg7_expr]

for df in data:
    df.drop('ATG7_y', axis = 1, inplace=True) 
    df.rename(columns = {'ATG7_x' : 'ATG7'}, inplace=True)
    verif = df[df.columns[pandas.Series(df.columns).str.startswith('ATG7')]]
    print(verif.head(2))

    ATG7  ATG7_1  ATG7_2
0  4.824   3.239   1.903
1  4.790   4.056   1.151

In [35]:
#save to csv
# symbol_normal_liver_protcoding_atg7_expr.to_csv('symbol_normal_liver_atg7_ProteinGE.csv', sep = "\t", index=False)
# symbol_primary_liver_protcoding_atg7_expr.to_csv('symbol_primary_liver_atg7_ProteinGE.csv', sep = "\t", index=False)